struct UBO
{
    uInvSize : vec4f,
    uScale : vec4f,
}

@group(0) @binding(4) var<uniform> _46 : UBO;
@group(0) @binding(0) var uHeight : texture_2d<f32>;
@group(0) @binding(16) var uHeight_sampler : sampler;
@group(0) @binding(1) var uDisplacement : texture_2d<f32>;
@group(0) @binding(17) var uDisplacement_sampler : sampler;
@group(0) @binding(2) var iHeightDisplacement : texture_storage_2d<rgba16float, write>;
@group(0) @binding(3) var iGradJacobian : texture_storage_2d<rgba16float, write>;

var<private> gl_GlobalInvocationID : vec3u;

fn jacobian(dDdx : vec2f, dDdy : vec2f) -> f32
{
    return ((1.0f + dDdx.x) * (1.0f + dDdy.y)) - (dDdx.y * dDdy.x);
}

fn comp_main()
{
    let uv = (vec2f(gl_GlobalInvocationID.xy) * _46.uInvSize.xy).xyxy + (_46.uInvSize * 0.5f);
    let h = textureSampleLevel(uHeight, uHeight_sampler, uv.xy, 0.0f).x;
    let x0 = textureSampleLevel(uHeight, uHeight_sampler, uv.xy, 0.0f, vec2i(-1, 0)).x;
    let x1 = textureSampleLevel(uHeight, uHeight_sampler, uv.xy, 0.0f, vec2i(1, 0)).x;
    let y0 = textureSampleLevel(uHeight, uHeight_sampler, uv.xy, 0.0f, vec2i(0, -1)).x;
    let y1 = textureSampleLevel(uHeight, uHeight_sampler, uv.xy, 0.0f, vec2i(0, 1)).x;
    let grad = (_46.uScale.xy * 0.5f) * vec2f(x1 - x0, y1 - y0);
    var displacement = textureSampleLevel(uDisplacement, uDisplacement_sampler, uv.zw, 0.0f).xy * 1.2000000476837158203125f;
    let dDdx = (textureSampleLevel(uDisplacement, uDisplacement_sampler, uv.zw, 0.0f, vec2i(1, 0)).xy - textureSampleLevel(uDisplacement, uDisplacement_sampler, uv.zw, 0.0f, vec2i(-1, 0)).xy) * 0.60000002384185791015625f;
    let dDdy = (textureSampleLevel(uDisplacement, uDisplacement_sampler, uv.zw, 0.0f, vec2i(0, 1)).xy - textureSampleLevel(uDisplacement, uDisplacement_sampler, uv.zw, 0.0f, vec2i(0, -1)).xy) * 0.60000002384185791015625f;
    let param = dDdx * _46.uScale.z;
    let param_1 = dDdy * _46.uScale.z;
    let j = jacobian(param, param_1);
    displacement = vec2f(0.0f);
    textureStore(iHeightDisplacement, bitcast<vec2i>(gl_GlobalInvocationID.xy), vec4f(h, displacement, 0.0f));
    textureStore(iGradJacobian, bitcast<vec2i>(gl_GlobalInvocationID.xy), vec4f(grad, j, 0.0f));
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(8, 8, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
