fn out_test_0(cond : i32, i : ptr<function, i32>)
{
    if (cond == 0)
    {
        (*i) = 40;
    }
    else
    {
        (*i) = 60;
    }
}

fn out_test_1(cond : i32, i : ptr<function, i32>)
{
    switch (cond)
    {
        case 40:
        {
            (*i) = 40;
            break;
        }
        default:
        {
            (*i) = 70;
            break;
        }
    }
}

fn inout_test_0(cond : i32, i : ptr<function, i32>)
{
    if (cond == 0)
    {
        (*i) = 40;
    }
}

fn inout_test_1(cond : i32, i : ptr<function, i32>)
{
    switch (cond)
    {
        case 40:
        {
            (*i) = 40;
            break;
        }
        default:
        {
            break;
        }
    }
}

fn comp_main()
{
    let cond = 40;
    var i = 50;
    let param = cond;
    var param_1 = i;
    out_test_0(param, &param_1);
    i = param_1;
    let param_2 = cond;
    var param_3 = i;
    out_test_1(param_2, &param_3);
    i = param_3;
    let param_4 = cond;
    var param_5 = i;
    inout_test_0(param_4, &param_5);
    i = param_5;
    let param_6 = cond;
    var param_7 = i;
    inout_test_1(param_6, &param_7);
    i = param_7;
}

@compute @workgroup_size(1, 1, 1)
fn main()
{
    comp_main();
}
