struct SSBO
{
    data : f32,
}

const gl_WorkGroupSize : vec3u = vec3u(1u);

@group(0) @binding(0) var<storage, read_write> _11 : SSBO;

fn test()
{
    if (_11.data != 0.0f)
    {
        var tmp : f32 = 10.0f;
        _11.data = tmp;
    }
    else
    {
        var tmp_1 : f32 = 15.0f;
        _11.data = tmp_1;
    }
    if (_11.data != 0.0f)
    {
        var e : f32;
        if (_11.data != 5.0f)
        {
            if (_11.data != 6.0f)
            {
                e = 10.0f;
            }
        }
        else
        {
            e = 20.0f;
        }
    }
    switch (i32(_11.data))
    {
        case 0:
        {
            var tmp_2 : f32 = 20.0f;
            _11.data = tmp_2;
            break;
        }
        case 1:
        {
            var tmp_3 : f32 = 30.0f;
            _11.data = tmp_3;
            break;
        }
        default:
        {
            break;
        }
    }
    var f : f32;
    switch (i32(_11.data))
    {
        case 0:
        {
            f = 30.0f;
            break;
        }
        case 1:
        {
            f = 40.0f;
            break;
        }
        default:
        {
            break;
        }
    }
    var i : i32 = 0;
    var h : f32;
    loop
    {
        var _86 : i32 = i;
        var _88 : bool = _86 < 20;
        if (_88)
        {
            i++;
            h += 10.0f;
            continue;
        }
        else
        {
            break;
        }
    }
    _11.data = h;
    var m : f32;
    loop
    {
        continuing
        {
            break if !(m != 20.0f);
        }
    }
    _11.data = m;
}

fn comp_main()
{
    test();
}

@compute @workgroup_size(1, 1, 1)
fn main()
{
    comp_main();
}
