struct SSBO0
{
    _as : array<vec4f>,
}

struct SSBO1
{
    bs : array<vec4f>,
}

const _66 : array<vec4f, 2> = array<vec4f, 2>(vec4f(10.0f), vec4f(30.0f));

struct Composite
{
    a : array<vec4f, 2>,
    b : array<vec4f, 2>,
}

const _94 : array<array<f32, 3>, 2> = array<array<f32, 3>, 2>(array<f32, 3>(1.0f, 1.0f, 1.0f), array<f32, 3>(2.0f, 2.0f, 2.0f));
const gl_WorkGroupSize : vec3u = vec3u(1u);

@group(0) @binding(0) var<storage, read_write> _41 : SSBO0;
@group(0) @binding(1) var<storage, read_write> _55 : SSBO1;

var<private> gl_GlobalInvocationID : vec3u;

fn summe(values : array<array<vec4f, 2>, 3>) -> vec4f
{
    return ((values[0][0] + values[2][1]) + values[0][1]) + values[1][0];
}

fn comp_main()
{
    var values : array<vec4f, 2> = array<vec4f, 2>(_41._as[gl_GlobalInvocationID.x], _55.bs[gl_GlobalInvocationID.x]);
    var copy_values : array<vec4f, 2> = _66;
    var copy_values2 : array<vec4f, 2> = values;
    var param : array<array<vec4f, 2>, 3> = array<array<vec4f, 2>, 3>(values, copy_values, copy_values2);
    _41._as[gl_GlobalInvocationID.x] = summe(param);
    var c : Composite = Composite(values, copy_values);
    var b : f32 = 10.0f;
    var values_scalar : array<f32, 4> = array<f32, 4>(b, b, b, b);
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(1, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
