struct SSBO
{
    data : vec4f,
    index : i32,
}

@group(0) @binding(0) var<storage, read_write> _13 : SSBO;

fn comp_main()
{
    let d = _13.data;
    _13.data = vec4f(d.x, d.yz + vec2f(10.0f), d.w);
    _13.data = (d + d) + d;
    _13.data = (d.yz + vec2f(10.0f)).xxyy;
    var t = (d.yz + vec2f(10.0f)).y;
    _13.data = vec4f(t);
    t = (d.zw + vec2f(10.0f))[_13.index];
    _13.data = vec4f(t);
}

@compute @workgroup_size(1, 1, 1)
fn main()
{
    comp_main();
}
