struct Distribution
{
    distribution : array<vec2f>,
}

struct UBO
{
    uModTime : vec4f,
}

struct HeightmapFFT
{
    heights : array<u32>,
}

@group(0) @binding(0) var<storage, read> _137 : Distribution;
@group(0) @binding(2) var<uniform> _166 : UBO;
@group(0) @binding(1) var<storage, read_write> _225 : HeightmapFFT;

var<private> gl_NumWorkGroups : vec3u;
var<private> gl_GlobalInvocationID : vec3u;

fn workaround_mix(a : vec2u, b : vec2u, sel : vec2<bool>) -> vec2u
{
    var _86 : u32;
    if (sel.x)
    {
        _86 = b.x;
    }
    else
    {
        _86 = a.x;
    }
    var _97 : u32;
    if (sel.y)
    {
        _97 = b.y;
    }
    else
    {
        _97 = a.y;
    }
    return vec2u(_86, _97);
}

fn _alias(i : vec2f, N : vec2f) -> vec2f
{
    return select(i, i - N, i > (N * 0.5f));
}

fn cmul(a : vec2f, b : vec2f) -> vec2f
{
    let r3 = a.yx;
    let r1 = b.xx;
    let R0 = a * r1;
    let r2 = b.yy;
    let R1 = r2 * r3;
    return R0 + vec2f(-R1.x, R1.y);
}

fn pack2(v : vec2f) -> u32
{
    return pack2x16float(v);
}

fn generate_heightmap()
{
    let N = vec2u(64u, 1u) * gl_NumWorkGroups.xy;
    let i = gl_GlobalInvocationID.xy;
    let param = N - i;
    let param_1 = vec2u(0u);
    let param_2 = i == vec2u(0u);
    let wi = workaround_mix(param, param_1, param_2);
    var a = _137.distribution[(i.y * N.x) + i.x];
    var b = _137.distribution[(wi.y * N.x) + wi.x];
    let param_3 = vec2f(i);
    let param_4 = vec2f(N);
    let k = _166.uModTime.xy * _alias(param_3, param_4);
    let k_len = length(k);
    let w = sqrt(9.81000041961669921875f * k_len) * _166.uModTime.z;
    let cw = cos(w);
    let sw = sin(w);
    let param_5 = a;
    let param_6 = vec2f(cw, sw);
    a = cmul(param_5, param_6);
    let param_7 = b;
    let param_8 = vec2f(cw, sw);
    b = cmul(param_7, param_8);
    b = vec2f(b.x, -b.y);
    let res = a + b;
    let param_9 = res;
    _225.heights[(i.y * N.x) + i.x] = pack2(param_9);
}

fn comp_main()
{
    generate_heightmap();
}

struct SPIRV_Cross_Input
{
    @builtin(num_workgroups) gl_NumWorkGroups : vec3u,
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(64, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_NumWorkGroups = stage_input.gl_NumWorkGroups;
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
