struct SSBO
{
    out_data : array<vec4f>,
}

const gl_WorkGroupSize : vec3u = vec3u(1u);

@group(0) @binding(0) var<storage, read_write> _27 : SSBO;

var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    var v : vec4f;
    v.x = 10.0f;
    v.y = 30.0f;
    v.z = 70.0f;
    v.w = 90.0f;
    _27.out_data[gl_GlobalInvocationID.x] = v;
    _27.out_data[gl_GlobalInvocationID.x].y = 20.0f;
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(1, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
