struct SSBO2
{
    out_data : array<mat3x3f>,
}

@group(0) @binding(1) var<storage, read_write> _22 : SSBO2;

var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    let ident = gl_GlobalInvocationID.x;
    _22.out_data[ident] = mat3x3f(vec3f(10.0f), vec3f(20.0f), vec3f(40.0f));
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(1, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
