struct SSBO
{
    in_data : array<vec4f>,
}

struct SSBO2
{
    out_data : array<vec4f>,
}

@group(0) @binding(0) var<storage, read> _23 : SSBO;
@group(0) @binding(1) var<storage, read_write> _33 : SSBO2;

var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    let ident = gl_GlobalInvocationID.x;
    let v = _23.in_data[ident] - _33.out_data[ident] * floor(_23.in_data[ident] / _33.out_data[ident]);
    _33.out_data[ident] = v;
    let vu = bitcast<vec4u>(_23.in_data[ident]) % bitcast<vec4u>(_33.out_data[ident]);
    _33.out_data[ident] = bitcast<vec4f>(vu);
    let vi = bitcast<vec4i>(_23.in_data[ident]) % bitcast<vec4i>(_33.out_data[ident]);
    _33.out_data[ident] = bitcast<vec4f>(vi);
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(1, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
