struct Foo
{
    m : mat4x4f,
}

struct SSBO2
{
    out_data : array<Foo>,
}

struct SSBO
{
    in_data : array<Foo>,
}

const gl_WorkGroupSize : vec3u = vec3u(1u);

@group(0) @binding(1) var<storage, read_write> _23 : SSBO2;
@group(0) @binding(0) var<storage, read> _30 : SSBO;

var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    var ident : u32 = gl_GlobalInvocationID.x;
    _23.out_data[ident].m = _30.in_data[ident].m * _30.in_data[ident].m;
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(1, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
