struct _3
{
    _m0 : vec4i,
    _m1 : vec4u,
}

struct _4
{
    _m0 : vec4u,
    _m1 : vec4i,
}

@group(0) @binding(0) var<storage, read_write> _5 : _3;
@group(0) @binding(1) var<storage, read_write> _6 : _4;

fn comp_main()
{
    var _22 : vec4i = _5._m0;
    var _23 : vec4u = _5._m1;
    _6._m0 = bitcast<vec4u>(bitcast<vec4i>(_23) / _22);
    _6._m0 = bitcast<vec4u>(_22 / bitcast<vec4i>(_23));
    _6._m0 = vec4u(1u);
    _6._m0 = vec4u(1u);
    _6._m1 = vec4i(1);
    _6._m1 = vec4i(1);
    _6._m1 = bitcast<vec4i>(_23) / _22;
    _6._m1 = _22 / bitcast<vec4i>(_23);
}

@compute @workgroup_size(1, 1, 1)
fn main()
{
    comp_main();
}
