#version 450
layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba8) uniform readonly image2D uInput;
layout(binding = 1, rgba16f) uniform writeonly image2D uOutput;
layout(binding = 2, r32f) uniform image2DArray uLayers;
layout(binding = 3, r32ui) uniform writeonly uimage3D uVolume;

void main()
{
	ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(uInput);
	if (any(greaterThanEqual(coord, size)))
		return;

	vec4 c = imageLoad(uInput, coord);
	float layer = imageLoad(uLayers, ivec3(coord, 1)).x;
	imageStore(uLayers, ivec3(coord, 0), vec4(layer * 2.0));
	imageStore(uOutput, coord, c * layer);
	imageStore(uVolume, ivec3(coord, 2), uvec4(c * 255.0));
}
