#version 450
layout(local_size_x_id = 0, local_size_y = 2, local_size_z = 1) in;

layout(constant_id = 1) const int COUNT = 4;
layout(constant_id = 2) const float SCALE = 2.0;
layout(constant_id = 3) const bool ENABLE = true;
const int DOUBLE_COUNT = COUNT * 2;

layout(std430, binding = 0) buffer SSBO
{
	float data[];
} ssbo;

shared float cache[gl_WorkGroupSize.x * gl_WorkGroupSize.y];

void main()
{
	uint idx = gl_LocalInvocationIndex;
	cache[idx] = ssbo.data[gl_GlobalInvocationID.x];
	barrier();
	float s = 0.0;
	for (int i = 0; i < DOUBLE_COUNT; i++)
		s += cache[(idx + uint(i)) % (gl_WorkGroupSize.x * gl_WorkGroupSize.y)];
	if (ENABLE)
		s *= SCALE;
	ssbo.data[gl_GlobalInvocationID.x] = s;
}
