struct SSBO
{
    counter : atomic<u32>,
    signed_counter : atomic<i32>,
    values : array<atomic<u32>>,
}

@group(0) @binding(0) var<storage, read_write> ssbo : SSBO;

var<private> gl_LocalInvocationIndex : u32;
var<private> gl_GlobalInvocationID : vec3u;
var<workgroup> shared_counter : atomic<u32>;
var<workgroup> shared_values : array<atomic<i32>, 64>;

fn comp_main()
{
    if (gl_LocalInvocationIndex == 0u)
    {
        atomicStore(&shared_counter, 0u);
    }
    workgroupBarrier();
    let _22 = atomicAdd(&shared_counter, 1u);
    let _34 = atomicMax(&shared_values[gl_LocalInvocationIndex % 64u], bitcast<i32>(_22));
    workgroupBarrier();
    let _43 = atomicAdd(&ssbo.counter, _22);
    let _49 = atomicLoad(&shared_values[gl_LocalInvocationIndex]);
    let _50 = atomicMin(&ssbo.signed_counter, _49);
    let _58 = atomicOr(&ssbo.values[gl_GlobalInvocationID.x], 1u);
    let _62 = atomicXor(&ssbo.values[gl_GlobalInvocationID.x], 2u);
    let _67 = atomicAnd(&ssbo.values[gl_GlobalInvocationID.x], 3u);
    let _74 = atomicExchange(&ssbo.values[gl_GlobalInvocationID.x + 1u], 4u);
    let _81 = atomicCompareExchangeWeak(&ssbo.values[gl_GlobalInvocationID.x + 2u], _74, 5u).old_value;
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
    @builtin(local_invocation_index) gl_LocalInvocationIndex : u32,
}

@compute @workgroup_size(64, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
