struct SSBO
{
    counter : atomic<u32>,
    signed_counter : atomic<i32>,
    values : array<atomic<u32>>,
}

const gl_WorkGroupSize : vec3u = vec3u(64u, 1u, 1u);

@group(0) @binding(0) var<storage, read_write> ssbo : SSBO;

var<private> gl_LocalInvocationIndex : u32;
var<private> gl_GlobalInvocationID : vec3u;
var<workgroup> shared_counter : atomic<u32>;
var<workgroup> shared_values : array<atomic<i32>, 64>;

fn comp_main()
{
    if (gl_LocalInvocationIndex == 0u)
    {
        atomicStore(&shared_counter, 0u);
    }
    workgroupBarrier();
    var _22 : u32 = atomicAdd(&shared_counter, 1u);
    var _34 : i32 = atomicMax(&shared_values[gl_LocalInvocationIndex % 64u], bitcast<i32>(_22));
    workgroupBarrier();
    var _43 : u32 = atomicAdd(&ssbo.counter, _22);
    var _49 : i32 = atomicLoad(&shared_values[gl_LocalInvocationIndex]);
    var _50 : i32 = atomicMin(&ssbo.signed_counter, _49);
    var _58 : u32 = atomicOr(&ssbo.values[gl_GlobalInvocationID.x], 1u);
    var _62 : u32 = atomicXor(&ssbo.values[gl_GlobalInvocationID.x], 2u);
    var _67 : u32 = atomicAnd(&ssbo.values[gl_GlobalInvocationID.x], 3u);
    var _74 : u32 = atomicExchange(&ssbo.values[gl_GlobalInvocationID.x + 1u], 4u);
    var _81 : u32 = atomicCompareExchangeWeak(&ssbo.values[gl_GlobalInvocationID.x + 2u], _74, 5u).old_value;
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
    @builtin(local_invocation_index) gl_LocalInvocationIndex : u32,
}

@compute @workgroup_size(64, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    gl_LocalInvocationIndex = stage_input.gl_LocalInvocationIndex;
    comp_main();
}
