fn comp_main()
{
    workgroupBarrier();
    storageBarrier();
    textureBarrier();
    workgroupBarrier();
    textureBarrier();
    storageBarrier();
    storageBarrier();
    textureBarrier();
    workgroupBarrier();
    workgroupBarrier();
    workgroupBarrier();
    workgroupBarrier();
    workgroupBarrier();
    workgroupBarrier();
    workgroupBarrier();
}

@compute @workgroup_size(4, 1, 1)
fn main()
{
    comp_main();
}
