struct SSBO
{
    i : vec4i,
    u : vec4u,
    shift : i32,
    ushift : u32,
}

@group(0) @binding(0) var<storage, read_write> ssbo : SSBO;

fn comp_main()
{
    let _18 = ssbo.i;
    let _24 = ssbo.u;
    ssbo.i = ((_18 << vec4u(vec4i(ssbo.shift))) + (_18 >> vec4u(vec4i(bitcast<i32>(ssbo.ushift))))) + bitcast<vec4i>(_24 >> vec4u(3u));
    ssbo.u = (_24 << vec4u(2u)) ^ (_24 >> vec4u(vec4i(ssbo.shift)));
    ssbo.i += (((extractBits(_18, u32(1), u32(4)) + firstTrailingBit(_18)) + bitcast<vec4i>(firstLeadingBit(_24))) + bitcast<vec4i>(countOneBits(_24)));
    ssbo.u += ((insertBits(_24, vec4u(7u), u32(4), u32(3)) + reverseBits(_24)) + extractBits(_24, u32(ssbo.shift), u32(2)));
    ssbo.u.x += (pack4x8unorm(vec4f(0.5f)) + pack2x16float(vec2f(1.0f, 2.0f)));
    ssbo.i.x += bitcast<i32>(unpack2x16snorm(ssbo.u.y).x);
}

@compute @workgroup_size(1, 1, 1)
fn main()
{
    comp_main();
}
