struct SSBO
{
    in_data : array<f32>,
}

struct SSBO2
{
    out_data : array<f32>,
}

struct SSBO3
{
    count : atomic<u32>,
}

@group(0) @binding(0) var<storage, read> _22 : SSBO;
@group(0) @binding(1) var<storage, read_write> _38 : SSBO2;
@group(0) @binding(2) var<storage, read_write> _41 : SSBO3;

var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    let _28 = _22.in_data[gl_GlobalInvocationID.x];
    if (_28 > 12.0f)
    {
        let _45 = atomicAdd(&_41.count, 1u);
        _38.out_data[_45] = _28;
    }
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(4, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
