struct Distribution
{
    distribution : array<vec2f>,
}

struct UBO
{
    uModTime : vec4f,
}

struct HeightmapFFT
{
    heights : array<u32>,
}

@group(0) @binding(0) var<storage, read> _137 : Distribution;
@group(0) @binding(2) var<uniform> _166 : UBO;
@group(0) @binding(1) var<storage, read_write> _225 : HeightmapFFT;

var<private> gl_NumWorkGroups : vec3u;
var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    let _265 = vec2u(64u, 1u) * gl_NumWorkGroups.xy;
    let _270 = _265 - gl_GlobalInvocationID.xy;
    let _272 = gl_GlobalInvocationID.xy == vec2u(0u);
    var _460 : u32;
    if (_272.x)
    {
        _460 = 0u;
    }
    else
    {
        _460 = _270.x;
    }
    var _461 : u32;
    if (_272.y)
    {
        _461 = 0u;
    }
    else
    {
        _461 = _270.y;
    }
    let _277 = _265.x;
    let _281 = (gl_GlobalInvocationID.y * _277) + gl_GlobalInvocationID.x;
    let _291 = (_461 * _277) + _460;
    let _298 = vec2f(gl_GlobalInvocationID.xy);
    let _300 = vec2f(_265);
    let _310 = sqrt(9.81000041961669921875f * length(_166.uModTime.xy * select(_298, _298 - _300, _298 > (_300 * 0.5f)))) * _166.uModTime.z;
    let _317 = vec2f(cos(_310), sin(_310));
    let _391 = _317.xx;
    let _396 = _317.yy;
    let _399 = _396 * _137.distribution[_281].yx;
    let _426 = _396 * _137.distribution[_291].yx;
    let _434 = (_137.distribution[_291] * _391) + vec2f(-_426.x, _426.y);
    _225.heights[_281] = pack2x16float(((_137.distribution[_281] * _391) + vec2f(-_399.x, _399.y)) + vec2f(_434.x, -_434.y));
}

struct SPIRV_Cross_Input
{
    @builtin(num_workgroups) gl_NumWorkGroups : vec3u,
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(64, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_NumWorkGroups = stage_input.gl_NumWorkGroups;
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
