@group(0) @binding(0) var uInput : texture_storage_2d<rgba8unorm, read>;
@group(0) @binding(2) var uLayers : texture_storage_2d_array<r32float, read_write>;
@group(0) @binding(1) var uOutput : texture_storage_2d<rgba16float, write>;
@group(0) @binding(3) var uVolume : texture_storage_3d<r32uint, write>;

var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    switch (0)
    {
        default:
        {
            let _17 = bitcast<vec2i>(gl_GlobalInvocationID.xy);
            if (any(_17 >= vec2i(textureDimensions(uInput))))
            {
                break;
            }
            let _39 = textureLoad(uInput, _17);
            let _49 = _17.x;
            let _52 = textureLoad(uLayers, vec3i(_49, _17.y, 1).xy, vec3i(_49, _17.y, 1).z);
            textureStore(uLayers, vec3i(_49, _17.y, 0).xy, vec3i(_49, _17.y, 0).z, vec4f(_52.x * 2.0f));
            textureStore(uOutput, _17, _39 * _52.x);
            textureStore(uVolume, vec3i(_49, _17.y, 2), vec4u(_39 * 255.0f));
            break;
        }
    }
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(8, 8, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
