enable subgroups;

struct SSBO
{
    data : array<f32>,
}

@group(0) @binding(0) var<storage, read_write> ssbo : SSBO;

var<private> gl_GlobalInvocationID : vec3u;
var<private> gl_SubgroupSize : u32;
var<private> gl_SubgroupInvocationID : u32;

fn comp_main()
{
    let _25 = ssbo.data[gl_GlobalInvocationID.x];
    let _29 = subgroupAdd(_25);
    let _32 = subgroupExclusiveAdd(_25);
    let _35 = subgroupMax(_25);
    let _38 = subgroupBroadcastFirst(_25);
    let _42 = subgroupShuffleXor(_25, 1u);
    let _49 = _25 > 0.0f;
    let _50 = subgroupBallot(_49);
    let _55 = subgroupAll(_49);
    let _56 = subgroupElect();
    if (_56)
    {
        ssbo.data[0] = _29;
    }
    ssbo.data[gl_GlobalInvocationID.x] = ((((((_32 + _35) + _38) + _42) + f32(_50.x)) + f32(gl_SubgroupSize)) + f32(gl_SubgroupInvocationID)) + select(0.0f, 1.0f, _55);
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
    @builtin(subgroup_size) gl_SubgroupSize : u32,
    @builtin(subgroup_invocation_id) gl_SubgroupInvocationID : u32,
}

@compute @workgroup_size(64, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    gl_SubgroupSize = stage_input.gl_SubgroupSize;
    gl_SubgroupInvocationID = stage_input.gl_SubgroupInvocationID;
    comp_main();
}
