struct S0
{
    a : vec4f,
}

struct SSBO0
{
    s0s : array<S0>,
}

struct S1
{
    a : vec4f,
}

struct SSBO1
{
    s1s : array<S1>,
}

struct SSBO2
{
    outputs : array<vec4f>,
}

@group(0) @binding(0) var<storage, read_write> _36 : SSBO0;
@group(0) @binding(1) var<storage, read_write> _55 : SSBO1;
@group(0) @binding(2) var<storage, read_write> _66 : SSBO2;

var<private> gl_GlobalInvocationID : vec3u;

fn comp_main()
{
    _66.outputs[gl_GlobalInvocationID.x] = _36.s0s[gl_GlobalInvocationID.x].a + _55.s1s[gl_GlobalInvocationID.x].a;
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(1, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
