struct ssbo
{
    _data : array<u32>,
}

@group(0) @binding(1) var<storage, read> ssbo_1 : ssbo;

var<private> gl_GlobalInvocationID : vec3u;

fn Load(size : u32)
{
    let byteAddrTemp = bitcast<i32>(size >> u32(2));
    let data = vec4u(ssbo_1._data[byteAddrTemp], ssbo_1._data[byteAddrTemp + 1], ssbo_1._data[byteAddrTemp + 2], ssbo_1._data[byteAddrTemp + 3]);
}

fn _main(id : vec3u)
{
    let param = 4u;
    Load(param);
}

fn comp_main()
{
    let id = gl_GlobalInvocationID;
    let param = id;
    _main(param);
}

struct SPIRV_Cross_Input
{
    @builtin(global_invocation_id) gl_GlobalInvocationID : vec3u,
}

@compute @workgroup_size(1, 1, 1)
fn main(stage_input : SPIRV_Cross_Input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
