struct SSBO
{
    a1 : f32,
    a2 : vec2f,
    a3 : vec3f,
    a4 : vec4f,
    b1 : f32,
    b2 : vec2f,
    b3 : vec3f,
    b4 : vec4f,
    c1 : f32,
    c2 : vec2f,
    c3 : vec3f,
    c4 : vec4f,
}

@group(0) @binding(0) var<storage, read_write> _4 : SSBO;

fn comp_main()
{
    _4.a1 = min(_4.b1, _4.c1);
    _4.a2 = min(_4.b2, _4.c2);
    _4.a3 = min(_4.b3, _4.c3);
    _4.a4 = min(_4.b4, _4.c4);
    _4.a1 = max(_4.b1, _4.c1);
    _4.a2 = max(_4.b2, _4.c2);
    _4.a3 = max(_4.b3, _4.c3);
    _4.a4 = max(_4.b4, _4.c4);
    _4.a1 = clamp(_4.a1, _4.b1, _4.c1);
    _4.a2 = clamp(_4.a2, _4.b2, _4.c2);
    _4.a3 = clamp(_4.a3, _4.b3, _4.c3);
    _4.a4 = clamp(_4.a4, _4.b4, _4.c4);
    var i : i32 = 0;
    loop
    {
        var _120 : i32 = i;
        var _121 : bool = _120 < 2;
        if (_121)
        {
            _4.a2 = min(_4.b2, _4.c2);
            i++;
            _4.a1 = clamp(_4.a1, _4.b2.x, _4.b2.y);
            continue;
        }
        else
        {
            break;
        }
    }
}

@compute @workgroup_size(1, 1, 1)
fn main()
{
    comp_main();
}
