struct BUF
{
    a : i32,
    b : i32,
    d : i32,
}

@group(0) @binding(0) var<storage, read_write> o : BUF;

fn comp_main()
{
    var c = o.a;
    var a : i32;
    loop
    {
        var _17_ladder_break : bool = false;
        switch (c)
        {
            case 5:
            {
                loop
                {
                    var _25_ladder_break : bool = false;
                    switch (o.d)
                    {
                        case 10, 20:
                        {
                            c += c;
                            _25_ladder_break = true;
                            break;
                        }
                        default:
                        {
                            continue;
                        }
                    }
                    if (_25_ladder_break)
                    {
                        break;
                    }
                }
                break;
            }
            case 1, 2, 3:
            {
                a = c;
                _17_ladder_break = true;
                break;
            }
            default:
            {
                break;
            }
        }
        if (_17_ladder_break)
        {
            break;
        }
        c++;
        continue;
    }
    o.b = a;
}

@compute @workgroup_size(1, 1, 1)
fn main()
{
    comp_main();
}
